spring.application.name=careroute
spring.datasource.url=jdbc:postgresql://localhost:${DATABASE_PORT:5432}/${DATABASE_DB:careroute}
spring.datasource.username=${DATABASE_USER:careroute}
spring.datasource.password=${DATABASE_PASSWORD:careroute}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configurations (bound to environment variables with fallback defaults)
security.jwt.secret-key=${JWT_SECRET_KEY:mySecretKeyMustBeAtLeast32BytesLongToSatisfyHmacSha256Requirements}
security.jwt.expiration-time=${JWT_EXPIRATION_TIME:86400000}
security.jwt.cookie-secure=${JWT_COOKIE_SECURE:false}